# Generated by Django 2.0.1 on 2018-03-02 10:45

import dj.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0013_auto_20180213_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_payment_voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Основание')),
                ('sum', models.FloatField(verbose_name='Выданная сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время написания')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('approved', 'Утвержден')], default='created', max_length=300, verbose_name='Статус')),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='panel.profileuser', verbose_name='Кому выдана')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='docflow_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='docflowfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sourcefile', models.FileField(max_length=500, upload_to=dj.views.make_upload_file, verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Описание файла')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docflow.cash_payment_voucher')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='cash_payment_voucher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflow.docflow_category', verbose_name='Категория ордера'),
        ),
        migrations.AddField(
            model_name='cash_payment_voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.profileuser', verbose_name='Кто выдал'),
        ),
    ]
