# Generated by Django 2.0.1 on 2018-03-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_payment_voucher',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='panel.profileuser', verbose_name='Кому выдана'),
        ),
    ]
