# Generated by Django 2.0.1 on 2018-03-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0040_shopstock_type'),
        ('docflow', '0003_auto_20180306_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_payment_voucher',
            name='kontragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kontragent', to='node.kontragent', verbose_name='Кому выдана (контрагент)'),
        ),
        migrations.AlterField(
            model_name='cash_payment_voucher',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to='panel.profileuser', verbose_name='Кому выдана (сотрудник)'),
        ),
    ]
