#!/bin/bash


##PARSE
./parse4discount.py
./parse4product.py
./parse4stock.py
./parse4price.py
./parse4artikul.py
./parse4buyer.py
./parse4deti.py
#./parse4check.py
##EXPORT
./crm2bit4price.py
./crm2bit4stock.py
##
./bit2crm4status.py
./bit2crm4bname.py
./bit2crm4nabor.py
./bit2crm4demovideotouch.py
./bit2crm4section.py
#./crm2bit4artikul.py
##
./bit2crm4prop.py
./bit2crm4propval.py #DELETE PROP
./bit2crm4propabc.py
#
./qrcodegen.py
./bit2crm4image.py
#log
./commonlog.py